#Github Release

- name: Release
  id: create_release
  uses: actions/create-release@v1
  with:
    release_name: Release v.${{ env.VERSION_NAME }}
    draft: false
    prerelease: false
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}